/* 
* semantic_functions.h
* ============================================================
 * Semantic analyzer header for the IFJ25 project.
 * ============================================================
 * Authors: Jakub Kosinka xkosinj00 FIT VUT v Brně
 * ============================================================
 * Date: 2025
 */

#ifndef SEMANTIC_ANALYZATOR_H
#define SEMANTIC_ANALYZATOR_H
#include "symtable.h"
#include "token.h"
#include "syntaktik_tree.h"
#include <stdio.h>
#include <stdlib.h>

typedef enum {
    VAR_TYPE_NUM,
    VAR_TYPE_STRING,
    VAR_TYPE_BOOL,
    VAR_TYPE_NULL,
    VAR_TYPE_UNDEFINED
}VarType;

/**
 * @file semantic_analyzator.h
 * @brief Header file for semantic analyzer module.
 *
 * This module provides functions for performing semantic analysis
 * on the abstract syntax tree (AST) generated by the syntactic analyzer.
 */

/**
 * @brief Add a getter function to the symbol table.
 * @param symptable Pointer to the symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the getter function.
 * @return 0 on success, 1 on redefinition error, -1 on memory allocation failure, -2 on other errors.
 */
int addGetterFunction(Node **symptable, Token *identifierToken);

/**
* @brief Add a setter function to the symbol table.
* @param symptable Pointer to the symbol table (binary tree).
* @param identifierToken Token representing the identifier of the setter function.
* @return 0 on success, 1 on redefinition error, -1 on memory allocation failure.
*/
int addSetterFunction(Node **symptable, Token *identifierToken);

/**
 * @brief Add a regular function to the symbol table.
 * @param symptable Pointer to the symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the function.
 * @param numberOfParams Number of parameters the function takes.
 * @return 0 on success, 1 on redefinition error, -1 on memory allocation failure.
 */
int addFunction(Node **symptable, Token *identifierToken, int numberOfParams);

/**
 * @brief Add a variable to the symbol table.
 * @param symptable Pointer to the symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the variable.
 * @param variableType Type of the variable.
 * @return 0 on success, 1 on redefinition error, -1 on memory allocation failure.
 */
int addVariable(Node **symptable, Token *identifierToken, VarType variableType);

/**
 * @brief Check if a getter function is defined in the symbol table.
 * @param symptable Pointer to the symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the function.
 * @return 1 if defined, 0 if not defined.
 */
int isGetterFunctionDefined(Node *symptable, Token *identifierToken);

/**
 * @brief Check if a setter function is defined in the symbol table.
 * @param symptable Pointer toToken *identifierToken) the symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the function.
 * @return 1 if defined, 0 if not defined.
 */
int isSetterFunctionDefined(Node *symptable, Token *identifierToken);

/**
 * @brief Check if a function is defined in the symbol table.
 * @param symptable Pointer to the symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the function.
 * @param numberOfParams Number of parameters the function takes.
 * @return 1 if defined, 0 if not defined.
 */
int isFunctionDefined(Node *symptable, Token *identifierToken, int numberOfParams);

/**
 * @brief Check if a variable is defined in the symbol table.
 * @param symptable Pointer to the symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the variable.
 * @return 1 if defined, 0 if not defined.
 */
int isVariableDefined(Node *symptable, Token *identifierToken);

/**
 * @brief Check if an identifier represents a variable usage in an expression.
 * 
 * This helps distinguish between variable references and other identifier uses
 * like function names, class names, etc.
 * 
 * @param node AST node containing the identifier
 * @param parent_node Parent AST node for context
 * @return 1 if it's a variable usage, 0 otherwise
 */
int isVariableUsage(struct SyntaktikTreeNode *node, struct SyntaktikTreeNode *parent_node);



/**
 * @brief Get the type of a variable from the symbol table.
 * @param local_symtable Pointer to the local symbol table (binary tree).
 * @param global_symtable Pointer to the global symbol table (binary tree).
 * @param identifierToken Token representing the identifier of the variable.
 * @return Type of the variable, or VAR_TYPE_UNDEFINED if not found.
 */
VarType getVariableType(Node *local_symtable, Node *global_symtable, Token *identifierToken);

/**
 * @brief Check built-in function call parameters for type correctness.
 * @param functionToken Token representing the built-in function being called.
 * @param argumentTokens Array of tokens representing the arguments passed to the function.
 * @param numberOfArguments Number of arguments passed to the function.
 * @param returnType Pointer to VarType where the return type will be stored if the check is successful.
 * @return 0 if parameters are correct, 1 if there is a type mismatch, -1 on unknown built-in function, -2 on other errors.
 */
int checkBuiltInFunctionCallParams(Node* local_symtable, Node* global_symtable, Token *functionToken, Token **argumentTokens, int numberOfArguments, VarType *returnType);

/**
 * @brief Check types for arithmetic operations.
 * @param leftOperand Token representing the left operand.
 * @param rightOperand Token representing the right operand.
 * @return Resulting VarType after the operation, or VAR_TYPE_UNDEFINED on type error.
 */
VarType checkArithmeticAndStringOperationTypes(VarType leftType, VarType rightType, Token *operatorToken);

/**
 * @brief Check types for relational operations.
 * @param leftOperand Token representing the left operand.
 * @param rightOperand Token representing the right operand.
 * @return Resulting VarType after the operation, or VAR_TYPE_UNDEFINED on type error.
 */
VarType checkRelationalOperationTypes(VarType leftType, VarType rightType, Token *operatorToken);

/**
 * @brief Perform semantic analysis on the entire AST.
 * 
 * This function traverses the AST and performs various semantic checks including:
 * - Undefined function calls
 * - Type compatibility in expressions
 * - Variable usage before definition
 * - Built-in function parameter validation
 * 
 * @param ast_root Root node of the abstract syntax tree
 * @param global_symtable Pointer to the global symbol table
 * @return 0 on success, appropriate error code on semantic error
 */
int performSemanticAnalysis(struct SyntaktikTreeNode *ast_root, Node *global_symtable);

/**
 * @brief Traverse AST node and perform semantic checks recursively.
 * 
 * @param node Current AST node to analyze
 * @param global_symtable Global symbol table
 * @param local_symtable Local symbol table for current scope
 * @param current_class_name Name of current class being analyzed
 * @return 0 on success, appropriate error code on semantic error
 */
int analyzeASTNode(struct SyntaktikTreeNode *node, Node *global_symtable, Node *local_symtable, char *current_class_name);

/**
 * @brief Check if a function call is semantically valid.
 * 
 * This checks if the function is defined in the appropriate symbol table
 * and validates parameter count and types for built-in functions.
 * 
 * @param function_node AST node representing the function call
 * @param global_symtable Global symbol table
 * @param local_symtable Local symbol table
 * @param current_class_name Current class name
 * @return 0 on success, ERROR_SEMANTIC_UNDEFINED if function not found, other error codes for type mismatches
 */
int checkFunctionCall(struct SyntaktikTreeNode *function_node, Node *global_symtable, Node *local_symtable, char *current_class_name);


#endif // SEMANTIC_ANALYZATOR_H
